### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by ztbh** [liulihaocai/JSDec#3]
[![TIM-20200714154914.png](https://i.postimg.cc/QM4Wrg7W/TIM-20200714154914.png)](https://postimg.cc/949fd7JW)

**Comment by ztbh** [comment]
dec.js:52改eval(cjs + '}}}});');后v6可以了，v5还是不行

**Comment by ztbh** [comment]
换一个v6也不行，醉了

**Comment by hax0r31337** [comment]
抱歉能不能把代码发我看看

**Comment by hax0r31337** [comment]
感觉是代码做截取处理时出的问题

**Comment by hax0r31337** [comment]
感觉已经修复了
