### ISSUE TITLE
代码decode报格式错误

### ISSUE THREAD

**Issue by LOVECHEN** [liulihaocai/JSDec#4]
var encode_version = 'sojson.v4';var __0x97be=['wrhvwrdew61Cw4s0VMKsw6vDnsOJwr1wwpHDsMKJwqTDiU5zQcKKAA==','w5UfFsKEw61tFsOLwp0ub8Kmel3CrCU=','wr8Mwpg=','F3/DnwLDkw==','wq3CjMK4w4wC','w6lRwqIuJQ==','AMOzwpLDt8OvwphIPAklZcKRUcOtf8KXKBrDr8Kg','ecOSERXCoQ==','wpjDqsOCw610OcKYAAR5w5cQbRvCrQ==','wrrCkHDDmsOz','wrA+w5BlwpA=','w6NUQsORVQ==','SBPCqE/Dsg==','McOvMMOofGEgfDLDgcKHVMOhwog=','wrLDqMOxRDQ=','wq07woQ=','wrbChwgaXw==','w67DnMKLWsOB','CcOEwqxOw5Q=','wr9mUQ==','w7sQw4rCoSU=','CkvChQ==','wocTw658wrQ=','wpjDsgNxOg==','woPCjsKew7Au','I8OjwqVfw5d8','wopLwp18w5o=','aGsHwrEo','wrjCo8KXw4w/','w5ZzW8OQbTPChmE=','I8OqwrHDhHY=','MMOSLMOjYQ==','wp4dw6Vpwq7DhVXCl8K6w7zDlcKvMFDCmMOB'];(function(_0x3c4d18,_0x720c7c){var _0x458971=function(_0x100765){while(--_0x100765){_0x3c4d18['push'](_0x3c4d18['shift']());}};var _0x1b75ae=function(){var _0x5c55bd={'data':{'key':'cookie','value':'timeout'},'setCookie':function(_0x294f77,_0x1c5973,_0x198ac7,_0x2b7035){_0x2b7035=_0x2b7035||{};var _0x2d9700=_0x1c5973+'='+_0x198ac7;var _0x4b4eb6=0x0;for(var _0x4b4eb6=0x0,_0xd50af1=_0x294f77['length'];_0x4b4eb6<_0xd50af1;_0x4b4eb6++){var _0x4bbe7d=_0x294f77[_0x4b4eb6];_0x2d9700+=';\x20'+_0x4bbe7d;var _0xf2077e=_0x294f77[_0x4bbe7d];_0x294f77['push'](_0xf2077e);_0xd50af1=_0x294f77['length'];if(_0xf2077e!==!![]){_0x2d9700+='='+_0xf2077e;}}_0x2b7035['cookie']=_0x2d9700;},'removeCookie':function(){return'dev';},'getCookie':function(_0x3952d4,_0x2c5151){_0x3952d4=_0x3952d4||function(_0x4d4cba){return _0x4d4cba;};var _0x150555=_0x3952d4(new RegExp('(?:^|;\x20)'+_0x2c5151['replace'](/([.$?*|{}()[]\/+^])/g,'$1')+'=([^;]*)'));var _0x2e794e=function(_0x90636,_0x5a5c3f){_0x90636(++_0x5a5c3f);};_0x2e794e(_0x458971,_0x720c7c);return _0x150555?decodeURIComponent(_0x150555[0x1]):undefined;}};var _0x1c84ad=function(){var _0x311f6a=new RegExp('\x5cw+\x20*\x5c(\x5c)\x20*{\x5cw+\x20*[\x27|\x22].+[\x27|\x22];?\x20*}');return _0x311f6a['test'](_0x5c55bd['removeCookie']['toString']());};_0x5c55bd['updateCookie']=_0x1c84ad;var _0x472f3d='';var _0x24f8ba=_0x5c55bd['updateCookie']();if(!_0x24f8ba){_0x5c55bd['setCookie'](['*'],'counter',0x1);}else if(_0x24f8ba){_0x472f3d=_0x5c55bd['getCookie'](null,'counter');}else{_0x5c55bd['removeCookie']();}};_0x1b75ae();}(__0x97be,0xe6));var _0x2575=function(_0x185c9c,_0x5e2bf2){_0x185c9c=_0x185c9c-0x0;var _0x12acb0=__0x97be[_0x185c9c];if(_0x2575['initialized']===undefined){(function(){var _0x250a1d=typeof window!=='undefined'?window:typeof process==='object'&&typeof require==='function'&&typeof global==='object'?global:this;var _0x339d06='ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=';_0x250a1d['atob']||(_0x250a1d['atob']=function(_0x3dcdd6){var _0x414ca5=String(_0x3dcdd6)['replace'](/=+$/,'');for(var _0x527646=0x0,_0xf2fdd8,_0x300282,_0x34297c=0x0,_0x489d4d='';_0x300282=_0x414ca5['charAt'](_0x34297c++);~_0x300282&&(_0xf2fdd8=_0x527646%0x4?_0xf2fdd8*0x40+_0x300282:_0x300282,_0x527646++%0x4)?_0x489d4d+=String['fromCharCode'](0xff&_0xf2fdd8>>(-0x2*_0x527646&0x6)):0x0){_0x300282=_0x339d06['indexOf'](_0x300282);}return _0x489d4d;});}());var _0x3e4c37=function(_0x45461a,_0x7ecb76){var _0x32544e=[],_0x1ac268=0x0,_0xad860e,_0x8fd1e5='',_0x2374af='';_0x45461a=atob(_0x45461a);for(var _0x134f69=0x0,_0x3d79e4=_0x45461a['length'];_0x134f69<_0x3d79e4;_0x134f69++){_0x2374af+='%'+('00'+_0x45461a['charCodeAt'](_0x134f69)['toString'](0x10))['slice'](-0x2);}_0x45461a=decodeURIComponent(_0x2374af);for(var _0x3214f9=0x0;_0x3214f9<0x100;_0x3214f9++){_0x32544e[_0x3214f9]=_0x3214f9;}for(_0x3214f9=0x0;_0x3214f9<0x100;_0x3214f9++){_0x1ac268=(_0x1ac268+_0x32544e[_0x3214f9]+_0x7ecb76['charCodeAt'](_0x3214f9%_0x7ecb76['length']))%0x100;_0xad860e=_0x32544e[_0x3214f9];_0x32544e[_0x3214f9]=_0x32544e[_0x1ac268];_0x32544e[_0x1ac268]=_0xad860e;}_0x3214f9=0x0;_0x1ac268=0x0;for(var _0x2d7305=0x0;_0x2d7305<_0x45461a['length'];_0x2d7305++){_0x3214f9=(_0x3214f9+0x1)%0x100;_0x1ac268=(_0x1ac268+_0x32544e[_0x3214f9])%0x100;_0xad860e=_0x32544e[_0x3214f9];_0x32544e[_0x3214f9]=_0x32544e[_0x1ac268];_0x32544e[_0x1ac268]=_0xad860e;_0x8fd1e5+=String['fromCharCode'](_0x45461a['charCodeAt'](_0x2d7305)^_0x32544e[(_0x32544e[_0x3214f9]+_0x32544e[_0x1ac268])%0x100]);}return _0x8fd1e5;};_0x2575['rc4']=_0x3e4c37;_0x2575['data']={};_0x2575['initialized']=!![];}var _0x1feeb3=_0x2575['data'][_0x185c9c];if(_0x1feeb3===undefined){if(_0x2575['once']===undefined){var _0x558498=function(_0x58ae0d){this['rc4Bytes']=_0x58ae0d;this['states']=[0x1,0x0,0x0];this['newState']=function(){return'newState';};this['firstState']='\x5cw+\x20*\x5c(\x5c)\x20*{\x5cw+\x20*';this['secondState']='[\x27|\x22].+[\x27|\x22];?\x20*}';};_0x558498['prototype']['checkState']=function(){var _0xce8425=new RegExp(this['firstState']+this['secondState']);return this['runState'](_0xce8425['test'](this['newState']['toString']())?--this['states'][0x1]:--this['states'][0x0]);};_0x558498['prototype']['runState']=function(_0x37d68d){if(!Boolean(~_0x37d68d)){return _0x37d68d;}return this['getState'](this['rc4Bytes']);};_0x558498['prototype']['getState']=function(_0x1706e5){for(var _0x2b0763=0x0,_0x5a5f4f=this['states']['length'];_0x2b0763<_0x5a5f4f;_0x2b0763++){this['states']['push'](Math['round'](Math['random']()));_0x5a5f4f=this['states']['length'];}return _0x1706e5(this['states'][0x0]);};new _0x558498(_0x2575)['checkState']();_0x2575['once']=!![];}_0x12acb0=_0x2575['rc4'](_0x12acb0,_0x5e2bf2);_0x2575['data'][_0x185c9c]=_0x12acb0;}else{_0x12acb0=_0x1feeb3;}return _0x12acb0;};(function(){var _0xe655cb=function(){var _0x1623ac=!![];return function(_0x459bc0,_0x2b4d76){var _0x47bf96=_0x1623ac?function(){if(_0x2b4d76){var _0x4230d8=_0x2b4d76['apply'](_0x459bc0,arguments);_0x2b4d76=null;return _0x4230d8;}}:function(){};_0x1623ac=![];return _0x47bf96;};}();var _0x4cbe94={'EfPfv':function _0x2ba0a8(_0x285af2,_0x58edb3){return _0x285af2+_0x58edb3;},'fXhNq':function _0x2ec9d1(_0x5b885e,_0x147993,_0x432aa0){return _0x5b885e(_0x147993,_0x432aa0);},'dbMLm':function _0x31d5a1(_0x3b6e24){return _0x3b6e24();}};var _0x5de02a=new CSInterface();var _0x27265c=0xffffff,_0x55af42=0x0,_0x2244c8=0x888888,_0x5e0501=0xcccccc,_0x4f0fbb=0x444444;_0x5de02a[_0x2575('0x0','F]]E')](CSInterface[_0x2575('0x1','wTzq')],_0x163612);_0x4cbe94['dbMLm'](_0x163612);function _0x163612(){var _0x1f7bde={'uJeqZ':'bZn','WZumY':function _0x53abb3(_0xf904c7,_0xa963ec){return _0xf904c7(_0xa963ec);},'jgdjR':function _0x1af065(_0xd5b6b0,_0x3a5c64){return _0xd5b6b0+_0x3a5c64;},'OGQIH':'.editmod','AHJuJ':_0x2575('0x2','0S[U'),'yShHM':function _0x433702(_0x2df2cc,_0xfbb1df){return _0x2df2cc+_0xfbb1df;},'UdDJx':function _0x4571c6(_0xb9809a,_0x5e3e33){return _0xb9809a>_0x5e3e33;},'Jvlzv':function _0x37f32b(_0x543921,_0x48bdc2){return _0x543921!==_0x48bdc2;},'ycwSN':function _0x1ed4cb(_0x352c82,_0x108e9a){return _0x352c82>_0x108e9a;},'qmVjM':function _0x415c49(_0x267a9e,_0x2a971a){return _0x267a9e===_0x2a971a;},'FBgvw':_0x2575('0x3',']h3y'),'jnGKU':function _0x28231e(_0x3ca986,_0x431f53,_0x5b1ea3){return _0x3ca986(_0x431f53,_0x5b1ea3);}};if(_0x1f7bde[_0x2575('0x4','l6lv')]==='bZn'){var _0x31d4a1=_0xe655cb(this,function(){var _0x2b9fb2=function(){return'\x64\x65\x76';},_0x260fe3=function(){return'\x77\x69\x6e\x64\x6f\x77';};var _0x57da66=function(){var _0xba79d7=new RegExp('\x5c\x77\x2b\x20\x2a\x5c\x28\x5c\x29\x20\x2a\x7b\x5c\x77\x2b\x20\x2a\x5b\x27\x7c\x22\x5d\x2e\x2b\x5b\x27\x7c\x22\x5d\x3b\x3f\x20\x2a\x7d');return!_0xba79d7['\x74\x65\x73\x74'](_0x2b9fb2['\x74\x6f\x53\x74\x72\x69\x6e\x67']());};var _0x11144c=function(){var _0x4d0396=new RegExp('\x28\x5c\x5c\x5b\x78\x7c\x75\x5d\x28\x5c\x77\x29\x7b\x32\x2c\x34\x7d\x29\x2b');return _0x4d0396['\x74\x65\x73\x74'](_0x260fe3['\x74\x6f\x53\x74\x72\x69\x6e\x67']());};var _0x113822=function(_0xe703dd){var _0x58eaed=~-0x1>>0x1+0xff%0x0;if(_0xe703dd['\x69\x6e\x64\x65\x78\x4f\x66']('\x69'===_0x58eaed)){_0x2855ba(_0xe703dd);}};var _0x2855ba=function(_0x56d3ff){var _0x29580d=~-0x4>>0x1+0xff%0x0;if(_0x56d3ff['\x69\x6e\x64\x65\x78\x4f\x66']((!![]+'')[0x3])!==_0x29580d){_0x113822(_0x56d3ff);}};if(!_0x57da66()){if(!_0x11144c()){_0x113822('\x69\x6e\x64\u0435\x78\x4f\x66');}else{_0x113822('\x69\x6e\x64\x65\x78\x4f\x66');}}else{_0x113822('\x69\x6e\x64\u0435\x78\x4f\x66');}});_0x31d4a1();var _0x4c7012=_0x5de02a['getHostEnvironment']()['appSkinInfo'];if(_0x4c7012){var _0x24432d=_0x1f7bde[_0x2575('0x5','pK^K')](_0x12dcda,_0x4c7012['panelBackgroundColor'][_0x2575('0x6','0tQH')]);var _0x5bfd64=document[_0x2575('0x7','#5[c')]('body');_0x5bfd64[0x0][_0x2575('0x8','DMXJ')][_0x2575('0x9','xriA')]=_0x1f7bde[_0x2575('0xa','g6wM')]('#',_0x24432d);_0x1f7bde['WZumY']($,_0x1f7bde[_0x2575('0xb','F]]E')])['css'](_0x1f7bde[_0x2575('0xc','5r&F')],_0x1f7bde[_0x2575('0xa','g6wM')]('#',_0x24432d));function _0xc6806f(_0x4a5c15,_0x191e65){var _0x42c762={'sxZhr':'JwF','kRMys':function _0x4c212a(_0x4d738b,_0x443653){return _0x4d738b>_0x443653;}};if('ixV'===_0x42c762['sxZhr']){if(_0x42c762[_0x2575('0xd','(qcK')](_0x24432d,_0x4f0fbb)){}else{}}else{var _0x381c9a=document[_0x2575('0xe','%7wo')](_0x4a5c15);_0x381c9a['href']=_0x191e65;}}_0x24432d=_0x1f7bde['yShHM']('0x',_0x24432d);if(_0x1f7bde['UdDJx'](_0x24432d,_0x2244c8)){if(_0x24432d>_0x5e0501){if(_0x1f7bde[_0x2575('0xf','O*%R')](_0x2575('0x10',']h3y'),'HfH')){}else{}}else{}}else{if(_0x1f7bde[_0x2575('0x11','L2#x')](_0x24432d,_0x4f0fbb)){if(_0x1f7bde[_0x2575('0x12','c47v')](_0x1f7bde[_0x2575('0x13','nGO%')],_0x2575('0x14','hr^0'))){}else{}}else{}}}}else{hex=_0x1f7bde['yShHM'](computeValue(red,delta),computeValue(green,delta))+_0x1f7bde[_0x2575('0x15','nW$1')](computeValue,blue,delta);}}function _0x12dcda(_0x3399b0,_0x4a61e5,_0x5a9d92){function _0x38bdc1(_0x11409f,_0x1acdb9){var _0x2e0e82={'xjoPl':'1|2|3|4|0','yXSQu':function _0x4e9c6b(_0x295577,_0x207a0e){return _0x295577==_0x207a0e;},'QsyVf':function _0x3ac1a0(_0x13752f,_0x592651){return _0x13752f+_0x592651;},'fyjwj':function _0x4e91bb(_0x345537,_0x8428d0){return _0x345537(_0x8428d0);},'CogXO':function _0x1c036f(_0x117cdd,_0x2c3d64){return _0x117cdd<_0x2c3d64;},'vCqpt':function _0x2cc2cf(_0x3023c8,_0x37f91e){return _0x3023c8===_0x37f91e;},'jfdde':'ctQ','BuZmd':_0x2575('0x16','j8yh'),'ZceOY':function _0x5647b0(_0x2bcb0e,_0x1844ef){return _0x2bcb0e>_0x1844ef;}};var _0x283672=_0x2e0e82[_0x2575('0x17','F]]E')][_0x2575('0x18','ekgS')]('|'),_0x2edb73=0x0;while(!![]){switch(_0x283672[_0x2edb73++]){case'0':return _0x2e0e82[_0x2575('0x19','pK^K')](_0x2253ac[_0x2575('0x1a','nGO%')],0x1)?_0x2e0e82['QsyVf']('0',_0x2253ac):_0x2253ac;case'1':_0x11409f=Math[_0x2575('0x1b','wTzq')](_0x11409f);continue;case'2':var _0x2253ac=!_0x2e0e82['fyjwj'](isNaN,_0x1acdb9)?_0x11409f+_0x1acdb9:_0x11409f;continue;case'3':if(_0x2e0e82[_0x2575('0x1c','9bA3')](_0x2253ac,0x0)){if(_0x2e0e82['vCqpt'](_0x2e0e82['jfdde'],_0x2e0e82[_0x2575('0x1d','pK^K')])){_0x2253ac=0x0;}else{_0x2253ac=0x0;}}else if(_0x2e0e82['ZceOY'](_0x2253ac,0xff)){_0x2253ac=0xff;}continue;case'4':_0x2253ac=_0x2253ac[_0x2575('0x1e','5r&F')](0x10);continue;}break;}}var _0x1cb288='';if(_0x3399b0){with(_0x3399b0){_0x1cb288=_0x4cbe94['EfPfv'](_0x4cbe94[_0x2575('0x1f','LHNd')](_0x38bdc1,red,_0x5a9d92)+_0x4cbe94[_0x2575('0x20','%7wo')](_0x38bdc1,green,_0x5a9d92),_0x4cbe94['fXhNq'](_0x38bdc1,blue,_0x5a9d92));}}return _0x1cb288;}}());;encode_version = 'sojson.v4';

**Comment by hax0r31337** [comment]
嗯收到，我会尽快解决

**Comment by hax0r31337** [comment]
大佬能不能用insert code把代码框起来，因为Markdown语法。。。

**Comment by hax0r31337** [comment]
不用了，我已经找到问题了，尽快修复

**Comment by hax0r31337** [comment]
这次commit已经修复了这个问题，感谢反馈
